[package]
name = "ansible-inline-vaulter"
version = "0.4.0-alpha"
edition = "2021"
authors = ["Enrico Falanga <enrico.falanga@optionfactory.net>"]
description = "View or edit secret properties using Ansible inline vaulting."
license = "GPL-3"

[dependencies]
clap = { version = "4.6.6", features = ["derive"] }
clap-verbosity-flag = "3.0.4"
serde_yaml_ng = "0.10.0"
anyhow = "1.0.104"
log = "0.4.33"
regex = { version = "1.13.1", features = [] }
log4rs = "1.4.0"
shellexpand = "3.1.2"
ansible-vault = "0.2.1"
walkdir = "2.5.0"
colored = "3.1.1"
ratatui = "0.30.0"
crossterm = "0.29.0"
tempfile = "3.27.0"
shell-words = "1.1.1"

[package.metadata.release]
publish = false
tag-prefix = "v"
tag-name = "v{{version}}"
pre-release-commit-message = "chore(release): version {{version}}"
push = true