name: Rust

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Install minimal stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
      - name: Cache dependencies
        uses: actions/cache@v2
        env:
          cache-name: cache-dependencies
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin
            ~/.cargo/registry/index
            ~/.cargo/registry/cache
            target
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Cargo.lock') }}
      - name: Build
        run: cargo build --release
      - name: Run tests
        run: cargo test --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ansible-inline-vault-viewer
          path: target/release/ansible-inline-vault-viewer
