name: Rust

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  rust:
    runs-on: self-hosted
    steps:
      - name: Install build-essentials
        run: sudo apt install -y build-essential
      - uses: actions/checkout@v3
      - name: Install minimal stable
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Build
        run: cargo build --release
      - name: Cache dependencies
        uses: actions/cache@v3
        env:
          cache-name: cache-dependencies
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Run tests
        run: cargo test --verbose
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ansible-inline-vault-viewer
          path: target/release/ansible-inline-vault-viewer
